// Audience Hub installer (PRD §3/§14): opens a project-owner-initiated PR
// that wires a property up to the CrawlProof Audience Hub. Deterministic —
// no LLM. The PR:
//   1. installs/updates the stats.js snippet (reuses the tracker installer's
//      discovery + injection),
//   2. adds a small generated server helper for POST /api/events where the
//      stack supports it (we favor generated code over a package in v1 so
//      the diff is fully inspectable),
//   3. documents the required env vars in .env.example.
//
// CrawlProof never pushes to the default branch and never opens PRs without
// an explicit owner action (the route requires a session + project access).

import { env } from "@/lib/env";
import {
  createBranch,
  getFileContent,
  getRepo,
  openPullRequest,
  putFile,
} from "./repos";
import { findInstallCandidates, previewInstallAtPath } from "./install-tracker";

const SITE_ORIGIN = env.siteUrl.replace(/\/$/, "");
const BRANCH_PREFIX = "crawlproof/audience-hub";

export type DetectedStack =
  | "nextjs-app"
  | "nextjs-pages"
  | "vite"
  | "hono"
  | "express"
  | "static"
  | "unknown";

export type InstallMode = "browser_only" | "server_only" | "browser_and_server";

export interface AudienceInstallInput {
  token: string;
  owner: string;
  repo: string;
  projectId: string;
  /** Project domain, used in generated examples. */
  projectDomain?: string;
  rootPath?: string;
  installMode?: InstallMode;
}

export interface AudienceInstallResult {
  status: "opened" | "noop";
  prUrl?: string;
  prNumber?: number;
  branch?: string;
  stackDetected: DetectedStack;
  filesChanged: string[];
  detail: string;
}

/** Which stacks can host the generated Node server helper. */
const SERVER_CAPABLE: ReadonlySet<DetectedStack> = new Set([
  "nextjs-app",
  "nextjs-pages",
  "hono",
  "express",
]);

function joinRoot(root: string, path: string): string {
  return root ? `${root}/${path}` : path;
}

function normalizeRoot(p: string | undefined): string {
  if (!p) return "";
  return p.replace(/^\/+/, "").replace(/\/+$/, "");
}

/** Pure: classify a repo from its package.json text. Exported for tests. */
export function detectStackFromPackageJson(
  pkgJsonText: string | null,
  hints: { hasAppLayout?: boolean; hasPagesApp?: boolean; hasIndexHtml?: boolean } = {},
): DetectedStack {
  if (!pkgJsonText) {
    return hints.hasIndexHtml ? "static" : "unknown";
  }
  let deps: Record<string, string> = {};
  try {
    const parsed = JSON.parse(pkgJsonText) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    deps = { ...parsed.dependencies, ...parsed.devDependencies };
  } catch {
    return "unknown";
  }
  if (deps.next) {
    if (hints.hasPagesApp && !hints.hasAppLayout) return "nextjs-pages";
    return "nextjs-app";
  }
  if (deps.hono) return "hono";
  if (deps.express) return "express";
  if (deps.vite) return "vite";
  if (hints.hasIndexHtml) return "static";
  return "unknown";
}

export async function detectStack(input: {
  token: string;
  owner: string;
  repo: string;
  ref: string;
  root: string;
}): Promise<DetectedStack> {
  const read = (path: string) =>
    getFileContent({
      token: input.token,
      owner: input.owner,
      repo: input.repo,
      path: joinRoot(input.root, path),
      ref: input.ref,
    });

  const pkg = await read("package.json");
  const [appLayout, srcAppLayout, pagesApp, srcPagesApp, indexHtml] = await Promise.all([
    read("app/layout.tsx"),
    read("src/app/layout.tsx"),
    read("pages/_app.tsx"),
    read("src/pages/_app.tsx"),
    read("index.html"),
  ]);

  return detectStackFromPackageJson(pkg?.content ?? null, {
    hasAppLayout: !!(appLayout || srcAppLayout),
    hasPagesApp: !!(pagesApp || srcPagesApp),
    hasIndexHtml: !!indexHtml,
  });
}

/** Where the generated helper lives per stack. */
export function serverHelperPath(stack: DetectedStack): string | null {
  switch (stack) {
    case "nextjs-app":
    case "nextjs-pages":
      return "lib/crawlproof/server.ts";
    case "hono":
    case "express":
      return "src/lib/crawlproof.ts";
    default:
      return null;
  }
}

/** Generated server helper (PRD §6) — plain fetch, no dependency. */
export function generatedServerHelper(projectDomain: string | undefined): string {
  const domain = projectDomain ?? "your-project.example";
  return `// Generated by CrawlProof Audience Hub — safe to edit.
// Sends trusted server-side events (user/customer lifecycle) to CrawlProof.
// Docs: ${SITE_ORIGIN}/docs/stats-tracker

type CrawlProofEvent = {
  event: string;
  project?: string;
  email?: string;
  name?: string;
  user_id?: string;
  marketing_consent?: boolean;
  plan?: string;
  metadata?: Record<string, unknown>;
};

export async function sendCrawlProofEvent(event: CrawlProofEvent): Promise<void> {
  const ingestUrl =
    process.env.CRAWLPROOF_INGEST_URL || "${SITE_ORIGIN}/api/events";
  const projectKey = process.env.CRAWLPROOF_PROJECT_KEY;

  if (!projectKey) {
    console.warn("CRAWLPROOF_PROJECT_KEY is not set; skipping CrawlProof event");
    return;
  }

  try {
    const response = await fetch(ingestUrl, {
      method: "POST",
      headers: {
        Authorization: \`Bearer \${projectKey}\`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ project: "${domain}", ...event }),
    });
    if (!response.ok) {
      console.warn("CrawlProof ingest failed", response.status, await response.text());
    }
  } catch (err) {
    // Audience events are best-effort; never break the caller.
    console.warn("CrawlProof ingest error", err);
  }
}

// Example:
//   await sendCrawlProofEvent({
//     event: "user.created",
//     email: user.email,
//     name: user.name,
//     user_id: user.id,
//     marketing_consent: Boolean(user.marketingConsent),
//   });
`;
}

/** Generated browser helper for Vite/React SPAs (queues until stats.js loads). */
export function generatedClientHelper(): string {
  return `// Generated by CrawlProof Audience Hub — safe to edit.
// Thin wrapper over the stats.js queue: calls made before the script loads
// are buffered and replayed. Docs: ${SITE_ORIGIN}/docs/stats-tracker

type CrawlProofPayload = Record<string, unknown>;

declare global {
  interface Window {
    crawlproof?: ((method: string, ...args: unknown[]) => void) & { q?: unknown[][] };
  }
}

function cp(method: string, ...args: unknown[]): void {
  if (typeof window === "undefined") return;
  if (typeof window.crawlproof === "function" && !window.crawlproof.q) {
    window.crawlproof(method, ...args);
    return;
  }
  const stub = (window.crawlproof ??= Object.assign(
    (...queued: unknown[]) => {
      (stub.q ??= []).push(queued as unknown[]);
    },
    { q: [] as unknown[][] },
  ));
  stub.q!.push([method, ...args]);
}

export const crawlproof = {
  track: (event: string, payload?: CrawlProofPayload) => cp("track", event, payload),
  identify: (payload: CrawlProofPayload) => cp("identify", payload),
  consent: (payload: CrawlProofPayload) => cp("consent", payload),
  alias: (previousId: string) => cp("alias", previousId),
};

// Example:
//   crawlproof.identify({ email: user.email, user_id: user.id, marketing_consent: true });
`;
}

export function envExampleBlock(projectId: string): string {
  return `# CrawlProof Audience Hub (${SITE_ORIGIN})
CRAWLPROOF_PROJECT_ID=${projectId}
CRAWLPROOF_PROJECT_KEY=
CRAWLPROOF_INGEST_URL=${SITE_ORIGIN}/api/events
`;
}

export async function installAudienceHub(
  input: AudienceInstallInput,
): Promise<AudienceInstallResult> {
  const mode: InstallMode = input.installMode ?? "browser_and_server";
  const repoMeta = await getRepo({
    token: input.token,
    owner: input.owner,
    repo: input.repo,
  });
  const base = repoMeta.default_branch;
  const root = normalizeRoot(input.rootPath);

  const stack = await detectStack({
    token: input.token,
    owner: input.owner,
    repo: input.repo,
    ref: base,
    root,
  });

  // ── Compute browser-side change (stats.js snippet). ─────────────────────
  let trackerEdit: { path: string; sha: string; after: string } | null = null;
  let trackerAlready: string | null = null;
  if (mode !== "server_only") {
    const candidates = await findInstallCandidates({
      token: input.token,
      owner: input.owner,
      repo: input.repo,
      rootPath: input.rootPath,
    });
    for (const candidate of candidates) {
      const preview = await previewInstallAtPath({
        token: input.token,
        owner: input.owner,
        repo: input.repo,
        path: candidate.path,
        projectId: input.projectId,
      });
      if (preview.status === "already_installed") {
        trackerAlready = preview.path;
        break;
      }
      if (preview.status === "ready") {
        const file = await getFileContent({
          token: input.token,
          owner: input.owner,
          repo: input.repo,
          path: preview.path,
          ref: base,
        });
        if (file) {
          trackerEdit = { path: file.path, sha: file.sha, after: preview.after };
        }
        break;
      }
    }
  }

  // ── Compute server-side changes (helper + .env.example). ────────────────
  const wantServer = mode !== "browser_only" && SERVER_CAPABLE.has(stack);
  const wantClientHelper = mode !== "server_only" && stack === "vite";

  const helperRelPath = wantServer
    ? serverHelperPath(stack)!
    : wantClientHelper
      ? "src/lib/crawlproof.ts"
      : null;
  const helperPath = helperRelPath ? joinRoot(root, helperRelPath) : null;
  const helperContent = wantServer
    ? generatedServerHelper(input.projectDomain)
    : wantClientHelper
      ? generatedClientHelper()
      : null;

  let helperEdit: { path: string; sha?: string; content: string } | null = null;
  if (helperPath && helperContent) {
    const existing = await getFileContent({
      token: input.token,
      owner: input.owner,
      repo: input.repo,
      path: helperPath,
      ref: base,
    });
    if (!existing) {
      helperEdit = { path: helperPath, content: helperContent };
    } else if (existing.content !== helperContent) {
      helperEdit = { path: helperPath, sha: existing.sha, content: helperContent };
    }
  }

  let envEdit: { path: string; sha?: string; content: string } | null = null;
  if (wantServer) {
    const envPath = joinRoot(root, ".env.example");
    const existing = await getFileContent({
      token: input.token,
      owner: input.owner,
      repo: input.repo,
      path: envPath,
      ref: base,
    });
    if (!existing) {
      envEdit = { path: envPath, content: envExampleBlock(input.projectId) };
    } else if (!existing.content.includes("CRAWLPROOF_PROJECT_KEY")) {
      const sep = existing.content.endsWith("\n") ? "\n" : "\n\n";
      envEdit = {
        path: envPath,
        sha: existing.sha,
        content: existing.content + sep + envExampleBlock(input.projectId),
      };
    }
  }

  const edits = [
    trackerEdit
      ? { path: trackerEdit.path, sha: trackerEdit.sha, content: trackerEdit.after }
      : null,
    helperEdit,
    envEdit,
  ].filter(Boolean) as { path: string; sha?: string; content: string }[];

  if (edits.length === 0) {
    return {
      status: "noop",
      stackDetected: stack,
      filesChanged: [],
      detail: trackerAlready
        ? `Audience Hub already installed (tracker at ${trackerAlready}; helper and env docs up to date).`
        : "Nothing to change — Audience Hub files are already up to date.",
    };
  }

  // ── Branch, commit, PR. ──────────────────────────────────────────────────
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const branch = `${BRANCH_PREFIX}-${ts}`;
  await createBranch({
    token: input.token,
    owner: input.owner,
    repo: input.repo,
    newBranch: branch,
    fromBranch: base,
  });

  for (const edit of edits) {
    await putFile({
      token: input.token,
      owner: input.owner,
      repo: input.repo,
      path: edit.path,
      branch,
      message: "Install CrawlProof Audience Hub",
      contentUtf8: edit.content,
      sha: edit.sha,
    });
  }

  const pr = await openPullRequest({
    token: input.token,
    owner: input.owner,
    repo: input.repo,
    head: branch,
    base,
    title: "Install CrawlProof Audience Hub tracking and ingest",
    body: prBody({
      stack,
      trackerPath: trackerEdit?.path ?? trackerAlready,
      helperPath: helperEdit?.path ?? null,
      envPath: envEdit?.path ?? null,
      serverEnabled: wantServer,
    }),
  });

  return {
    status: "opened",
    prUrl: pr.html_url,
    prNumber: pr.number,
    branch,
    stackDetected: stack,
    filesChanged: edits.map((edit) => edit.path),
    detail: `Opened PR touching ${edits.map((edit) => edit.path).join(", ")} (stack: ${stack}).`,
  };
}

function prBody(input: {
  stack: DetectedStack;
  trackerPath: string | null;
  helperPath: string | null;
  envPath: string | null;
  serverEnabled: boolean;
}): string {
  const changes = [
    input.trackerPath
      ? `- Browser-side identity and lead capture via \`stats.js\` (\`${input.trackerPath}\`)`
      : null,
    input.helperPath
      ? input.serverEnabled
        ? `- Server-side event forwarding helper (\`${input.helperPath}\`)`
        : `- Typed browser helper for identify/track/consent (\`${input.helperPath}\`)`
      : null,
    input.envPath ? `- Environment variable documentation (\`${input.envPath}\`)` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const envSection = input.serverEnabled
    ? `
## Required Environment Variables

- \`CRAWLPROOF_PROJECT_ID\` — already filled in \`.env.example\`
- \`CRAWLPROOF_PROJECT_KEY\` — mint one on the project's Audience tab in CrawlProof
- \`CRAWLPROOF_INGEST_URL\` — defaults to \`${SITE_ORIGIN}/api/events\`
`
    : "";

  return `## Summary

This PR installs the CrawlProof Audience Hub integration for this property (detected stack: \`${input.stack}\`).

It adds or updates:

${changes}

## Events you can now send

- \`page_view\` (automatic)
- \`lead.captured\`
- \`newsletter.subscribed\`
- \`user.created\`
- \`customer.created\`
${envSection}
## Notes

CrawlProof uses these events to build a centralized, consent-aware audience
list across connected properties. Marketing consent is only ever recorded
from explicit signals — an account email is never auto-subscribed.

Docs: ${SITE_ORIGIN}/docs/stats-tracker`;
}
