// Source for the /careers page CrawlProof opens as a pull request.
//
// The careers widget already paints a board client-side, which is fine for
// people and useless for crawlers — a client-rendered job board is exactly the
// failure CrawlProof audits for. This module generates a real server-rendered
// route for the customer's own repo so the roles ship as HTML on their domain,
// with the JobPosting graph in the source rather than injected after load.
//
// Everything here is a pure string builder: no network, no repo access. That
// keeps the interesting part — what we are about to write into someone else's
// codebase — cheap to test exactly.
//
// The generated file is standalone by design. It cannot import from us, so the
// small amount of rendering logic below is duplicated into the output rather
// than shared. To stop that duplicate drifting, the generated code asks the
// feed for `json_ld` and `canonical_url` instead of recomputing schema.org
// itself; the only thing it owns is markup.

export type CareersFramework = "next-app" | "astro";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface TemplateInput {
  /** CrawlProof's origin, e.g. https://crawlproof.com */
  origin: string;
  projectId: string;
  /** Directory the route goes in, e.g. "app", "src/app", "src/pages". */
  dir: string;
  /** Emit type annotations. False for JavaScript repos, where they'd break the build. */
  typescript: boolean;
}

const JOB_FIELDS = [
  "slug",
  "title",
  "department",
  "location",
  "employment_type",
  "workplace",
  "compensation",
  "overview",
  "responsibilities",
  "qualifications",
  "canonical_url",
  "json_ld",
] as const;

function feedUrl(origin: string, projectId: string): string {
  return `${origin.replace(/\/+$/, "")}/api/careers/jobs?site=${projectId}`;
}

function dashboardUrl(origin: string, projectId: string): string {
  return `${origin.replace(/\/+$/, "")}/projects/${projectId}/stats/careers`;
}

/** The banner every generated file opens with. */
function header(origin: string, projectId: string): string {
  return [
    "// Careers page generated by CrawlProof.",
    "//",
    "// Roles are managed in the CrawlProof dashboard, not in this file:",
    `//   ${dashboardUrl(origin, projectId)}`,
    "//",
    "// This page server-renders the open roles so search engines and answer",
    "// engines can read them. If the CrawlProof tracker is installed, its",
    "// widget upgrades the same markup into an inline application form.",
    "//",
    "// Safe to restyle or restructure. Re-running the installer will not",
    "// overwrite it.",
  ].join("\n");
}

const JOB_TYPE = `type CareersJob = {
${JOB_FIELDS.map((field) => {
  if (field === "responsibilities" || field === "qualifications") return `  ${field}: string[];`;
  if (field === "json_ld") return `  ${field}: Record<string, unknown>;`;
  if (field === "department" || field === "location" || field === "compensation" || field === "overview") {
    return `  ${field}: string | null;`;
  }
  return `  ${field}: string;`;
}).join("\n")}
};`;

/**
 * The markup builders shared by every framework we support.
 *
 * Written as string concatenation rather than template literals so the output
 * is easy to read in a diff and impossible to break by interpolation.
 *
 * Exported so the tests can execute the untyped build and prove the escaping
 * holds, rather than only asserting the text looks right.
 */
export function renderHelpers(typescript: boolean): string {
  const t = (annotation: string) => (typescript ? annotation : "");
  const job = t(": CareersJob");
  const str = t(": string");

  return `function esc(value${t(": unknown")})${str} {
  return String(value == null ? "" : value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// A bare city already reads as on-site, so only remote and hybrid get labelled.
function placeLabel(job${job})${str} {
  var at = (job.location || "").trim();
  if (job.workplace === "remote") return at ? "Remote \\u00b7 " + at : "Remote";
  if (job.workplace === "hybrid") return at ? "Hybrid \\u00b7 " + at : "Hybrid";
  return at || "On-site";
}

function bullets(items${t(": string[]")}, heading${str})${str} {
  if (!items || items.length === 0) return "";
  return (
    "<h3>" + esc(heading) + "</h3><ul>" +
    items.map(function (item${str}) { return "<li>" + esc(item) + "</li>"; }).join("") +
    "</ul>"
  );
}

function jobCard(job${job})${str} {
  var meta = [placeLabel(job), job.department, job.employment_type, job.compensation]
    .filter(Boolean)
    .map(function (part) { return esc(part); })
    .join(" &middot; ");
  return [
    '<article class="cp-job" id="' + esc(job.slug) + '">',
    "<h2>" + esc(job.title) + "</h2>",
    '<p class="cp-job-meta">' + meta + "</p>",
    job.overview ? "<p>" + esc(job.overview) + "</p>" : "",
    bullets(job.responsibilities, "Responsibilities"),
    bullets(job.qualifications, "Qualifications"),
    '<p><a class="cp-job-apply" href="' + esc(job.canonical_url) + '">Apply for ' +
      esc(job.title) + "</a></p>",
    "</article>",
  ].join("");
}

// The JobPosting graph comes from the feed already built, so this file never
// has to keep a copy of the schema.org rules in sync.
function jsonLd(job${job})${str} {
  if (!job.json_ld) return "";
  var payload = JSON.stringify(job.json_ld).replace(/</g, "\\\\u003c");
  return '<script type="application/ld+json">' + payload + "</" + "script>";
}

function boardHtml(jobs${t(": CareersJob[]")})${str} {
  if (!jobs || jobs.length === 0) {
    return '<p class="cp-careers-empty">No open roles right now.</p>';
  }
  return jobs.map(jobCard).join("") + jobs.map(jsonLd).join("");
}`;
}

/** The fetch, written once. Failure renders an empty board, never an error page. */
function loader(typescript: boolean, options: string): string {
  const t = (annotation: string) => (typescript ? annotation : "");
  return `async function loadJobs()${t(": Promise<CareersJob[]>")} {
  try {
    var res = await fetch(FEED${options});
    if (!res.ok) return [];
    var payload = await res.json();
    return (payload && payload.jobs) || [];
  } catch {
    // A careers page that 500s because our API blinked is worse than one
    // that shows no roles for a few minutes.
    return [];
  }
}`;
}

function nextAppPage(input: TemplateInput): GeneratedFile[] {
  const ext = input.typescript ? "tsx" : "jsx";
  const content = `${header(input.origin, input.projectId)}

export const revalidate = 300;

const FEED = ${JSON.stringify(feedUrl(input.origin, input.projectId))};

${input.typescript ? `${JOB_TYPE}\n\n` : ""}${renderHelpers(input.typescript)}

${loader(input.typescript, ", { next: { revalidate: revalidate } }")}

export default async function CareersPage() {
  const jobs = await loadJobs();
  return (
    <main className="cp-careers-page">
      <h1>Open roles</h1>
      <div
        data-cp-careers
        data-cp-careers-ssr
        dangerouslySetInnerHTML={{ __html: boardHtml(jobs) }}
      />
    </main>
  );
}
`;
  return [{ path: `${input.dir}/careers/page.${ext}`, content }];
}

function astroPage(input: TemplateInput): GeneratedFile[] {
  const content = `---
${header(input.origin, input.projectId)}
//
// On a statically built Astro site this runs at build time, so new roles
// appear on your next deploy. Switch the route to on-demand rendering if you
// want them to appear immediately.

const FEED = ${JSON.stringify(feedUrl(input.origin, input.projectId))};

${JOB_TYPE}

${renderHelpers(true)}

${loader(true, "")}

const jobs = await loadJobs();
const html = boardHtml(jobs);
---

<main class="cp-careers-page">
  <h1>Open roles</h1>
  <div data-cp-careers data-cp-careers-ssr set:html={html}></div>
</main>
`;
  return [{ path: `${input.dir}/careers.astro`, content }];
}

/**
 * The route file(s) to write for a framework.
 *
 * Astro frontmatter is always TypeScript, so the `typescript` flag only
 * changes the Next output.
 */
export function careersRouteFiles(
  framework: CareersFramework,
  input: TemplateInput,
): GeneratedFile[] {
  return framework === "astro" ? astroPage(input) : nextAppPage(input);
}

/** Paths that would collide with the route we want to add. */
export function conflictingPaths(framework: CareersFramework, dir: string): string[] {
  if (framework === "astro") {
    return [`${dir}/careers.astro`, `${dir}/careers/index.astro`];
  }
  return ["tsx", "jsx", "ts", "js"].map((ext) => `${dir}/careers/page.${ext}`);
}
