import { serviceClient } from "@/lib/supabase/service";

function normalize(email: string): string | null {
  const e = email.trim().toLowerCase();
  if (!e || !e.includes("@")) return null;
  return e;
}

// Record a *lead* — an email we captured during a transaction (e.g.
// hero audit form), NOT a marketing opt-in. Inserts a marketing_contacts
// row with consented_at=NULL.
//
// Rule: never downgrade a prior consent to a lead. If a row already
// exists for this email, leave it alone (its consent state and source
// stay intact).
//
// Senders MUST filter `where consented_at is not null` before sending
// promotional email. Lead rows are for transactional / sales follow-up
// only.
export async function recordLead(input: {
  email: string;
  source: string;
}): Promise<void> {
  const email = normalize(input.email);
  if (!email) return;
  const svc = serviceClient();
  const { data: existing } = await svc
    .from("marketing_contacts")
    .select("id")
    .ilike("email", email)
    .maybeSingle();
  if (existing) return;
  const { error } = await svc.from("marketing_contacts").insert({
    email,
    source: input.source,
    consented_at: null,
  });
  if (error) {
    // Race window: another concurrent insert won the unique index. Fine.
    console.warn("[marketing.recordLead]", error.message);
  }
}

// Record an explicit marketing opt-in. Idempotent: if the email already has
// a row, we refresh consented_at and clear any prior unsubscribe (the user
// is opting in again, presumably knowingly). The unsubscribe_token is
// generated by the DB default on first insert and preserved on update.
export async function recordMarketingConsent(input: {
  email: string;
  source: string;
}): Promise<void> {
  const email = normalize(input.email);
  if (!email) return;
  const svc = serviceClient();
  const { error } = await svc
    .from("marketing_contacts")
    .upsert(
      {
        email,
        source: input.source,
        consented_at: new Date().toISOString(),
        unsubscribed_at: null,
      },
      { onConflict: "email", ignoreDuplicates: false },
    );
  if (error) {
    // Fallback if the unique conflict target is the lower(email) functional
    // index rather than the email column itself — try a manual update.
    const { data: existing } = await svc
      .from("marketing_contacts")
      .select("id")
      .ilike("email", email)
      .maybeSingle();
    if (existing) {
      await svc
        .from("marketing_contacts")
        .update({
          source: input.source,
          consented_at: new Date().toISOString(),
          unsubscribed_at: null,
        })
        .eq("id", existing.id);
    } else {
      await svc.from("marketing_contacts").insert({
        email,
        source: input.source,
      });
    }
  }
}

export async function unsubscribeByToken(
  token: string,
): Promise<{ ok: boolean; email?: string }> {
  if (!token || token.length < 8) return { ok: false };
  const svc = serviceClient();
  const { data, error } = await svc
    .from("marketing_contacts")
    .update({ unsubscribed_at: new Date().toISOString() })
    .eq("unsubscribe_token", token)
    .select("email")
    .maybeSingle();
  if (error || !data) return { ok: false };
  return { ok: true, email: data.email as string };
}

// Unsubscribe an imported org-audience contact (mass-email recipient). Marks
// the per-org row suppressed; the contact won't receive future org blasts.
export async function unsubscribeOrgAudienceByToken(
  token: string,
): Promise<{ ok: boolean; email?: string }> {
  if (!token || token.length < 8) return { ok: false };
  const svc = serviceClient();
  const { data, error } = await svc
    .from("organization_audience_contacts")
    .update({ unsubscribed_at: new Date().toISOString() })
    .eq("unsubscribe_token", token)
    .select("email")
    .maybeSingle();
  if (error || !data) return { ok: false };
  return { ok: true, email: data.email as string };
}
