// specification.website MCP engine — fetches the audit_url prompt from
// https://mcp.specification.website/mcp and converts the checklist into
// structured findings. Free; no LLM required.

import { fetchSpecAuditPlan } from "./spec-mcp";
import { scoreFindings } from "./score";
import type { AuditResult, Finding } from "./types";

type SpecAuditResult = AuditResult & { markdown: string };

// Each checklist item in the prompt looks like:
//   - **Item name** (required) — Description text.
//     Reference: https://specification.website/spec/…/
function planToFindings(plan: string): Finding[] {
  const findings: Finding[] = [];
  let idx = 0;

  const lines = plan.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!.trim();

    // Match: - **Title** (status) — Description
    const m = line.match(/^-\s+\*\*(.+?)\*\*\s+\((\w+)\)\s+[—–-]\s+(.+)/);
    if (!m) continue;

    const title = m[1]!.trim();
    const tier = m[2]!.toLowerCase(); // required | recommended | optional | avoid
    const description = m[3]!.trim();

    // Grab the Reference line if it follows immediately.
    const nextLine = lines[i + 1]?.trim() ?? "";
    const refMatch = nextLine.match(/^Reference:\s*(https?:\/\/\S+)/);
    const refUrl = refMatch?.[1];

    const detail = refUrl ? `${description}\n\nReference: ${refUrl}` : description;

    // required items start as warn (need attention); recommended/optional as unknown.
    const status = tier === "required" ? "warn" : "unknown";
    const priority: 1 | 2 | 3 | 4 | 5 = tier === "required" ? 2 : 4;

    findings.push({
      section: "Website Specification",
      check_key: `spec.mcp.${++idx}`,
      status,
      title: `[${tier}] ${title}`,
      detail,
      evidence: refUrl ? { reference: refUrl, tier } : { tier },
      priority,
    });
  }

  return findings;
}

export async function specAudit(targetUrl: string): Promise<SpecAuditResult> {
  const started = Date.now();

  const plan = await fetchSpecAuditPlan(targetUrl);

  if (!plan) {
    const findings: Finding[] = [
      {
        section: "Website Specification",
        check_key: "spec.mcp.unavailable",
        status: "warn",
        title: "specification.website MCP server did not respond",
        detail:
          "The audit checklist could not be retrieved from https://mcp.specification.website/mcp. The server may be temporarily unavailable.",
        priority: 3,
      },
    ];
    return {
      score: 50,
      findings,
      markdown: `# Website Specification Audit\n\n_Could not reach specification.website MCP server._\n`,
      summary: {
        pagesCrawled: 0,
        pass: 0,
        warn: 1,
        fail: 0,
        unknown: 0,
        dataFound: [],
        durationMs: Date.now() - started,
      },
    };
  }

  const findings = planToFindings(plan);
  const score = findings.length > 0 ? scoreFindings(findings) : 50;

  const markdown = [
    `# Website Specification Audit for ${targetUrl}`,
    ``,
    `Checklist generated by [specification.website](https://specification.website/) via its [MCP server](https://mcp.specification.website/mcp).`,
    `Required-tier items are shown as warnings until manually verified.`,
    ``,
    plan,
  ].join("\n");

  return {
    score,
    findings,
    markdown,
    summary: {
      pagesCrawled: 0,
      pass: findings.filter((f) => f.status === "pass").length,
      warn: findings.filter((f) => f.status === "warn").length,
      fail: findings.filter((f) => f.status === "fail").length,
      unknown: findings.filter((f) => f.status === "unknown").length,
      dataFound: [],
      durationMs: Date.now() - started,
    },
  };
}
