// specification.website MCP engine — calls the free public MCP server at
// https://mcp.specification.website/mcp and returns an audit plan as a
// structured AuditResult + markdown report.

import { fetchSpecAuditPlan } from "./spec-mcp";
import { scoreFindings } from "./score";
import type { AuditResult, Finding } from "./types";

type SpecAuditResult = AuditResult & { markdown: string };

// Parse the markdown audit plan returned by specification.website into
// individual Finding objects. The plan uses fenced sections (## Category)
// and checkbox lines (- [ ] item or - [x] item).
function planToFindings(plan: string): Finding[] {
  const findings: Finding[] = [];
  let currentSection = "Website Specification";
  let idx = 0;

  for (const raw of plan.split(/\r?\n/)) {
    const line = raw.trim();

    const headingMatch = line.match(/^#{1,3}\s+(.+)/);
    if (headingMatch) {
      currentSection = headingMatch[1]!.trim();
      continue;
    }

    const itemMatch = line.match(/^-\s+\[([ xX])\]\s+(.+)/);
    if (itemMatch) {
      const checked = itemMatch[1]!.toLowerCase() === "x";
      const text = itemMatch[2]!.trim();
      findings.push({
        section: "Website Specification",
        check_key: `spec.mcp.${++idx}`,
        status: checked ? "pass" : "warn",
        title: text.length > 140 ? text.slice(0, 140) + "…" : text,
        detail: `Category: ${currentSection}`,
        priority: 3,
      });
    }
  }

  return findings;
}

export async function specAudit(targetUrl: string): Promise<SpecAuditResult> {
  const started = Date.now();

  const plan = await fetchSpecAuditPlan(targetUrl);

  if (!plan) {
    const findings: Finding[] = [
      {
        section: "Website Specification",
        check_key: "spec.mcp.unavailable",
        status: "warn",
        title: "specification.website MCP server did not respond",
        detail:
          "The audit plan could not be retrieved. The MCP endpoint at https://mcp.specification.website/mcp may be temporarily unavailable.",
        priority: 3,
      },
    ];
    return {
      score: 50,
      findings,
      markdown: `# Website Specification Audit\n\n_Could not reach specification.website MCP server._\n`,
      summary: {
        pagesCrawled: 0,
        pass: 0,
        warn: 1,
        fail: 0,
        unknown: 0,
        dataFound: [],
        durationMs: Date.now() - started,
      },
    };
  }

  const findings = planToFindings(plan);

  // Score only the spec items (not the header finding).
  const score = findings.length > 0 ? scoreFindings(findings) : 50;

  const markdown = [
    `# Website Specification Audit for ${targetUrl}`,
    ``,
    `Generated by [specification.website](https://specification.website/) via its [MCP server](https://specification.website/mcp/).`,
    ``,
    plan,
  ].join("\n");

  return {
    score,
    findings,
    markdown,
    summary: {
      pagesCrawled: 0,
      pass: findings.filter((f) => f.status === "pass").length,
      warn: findings.filter((f) => f.status === "warn").length,
      fail: findings.filter((f) => f.status === "fail").length,
      unknown: findings.filter((f) => f.status === "unknown").length,
      dataFound: [],
      durationMs: Date.now() - started,
    },
  };
}
